### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.yaml'

### ISSUE THREAD

**Issue by ShanghaoLi0913** [cuongducle/Selenium_FB_Crawler#1]

**Comment by cuongducle** [comment]
you should create credentials.yaml file with content like this:
email: ***
password: ***

**Comment by ShanghaoLi0913** [comment]
> you should create credentials.yaml file with content like this:
> email: ***
> password: ***

Thanks! there is other problem 😭
`DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(
There's some error in log in.
<class 'selenium.common.exceptions.WebDriverException'>
`

**Comment by cuongducle** [comment]
I just fixed it. You can pull code and run again
